export const outreachDescription = [
  "Novus Outreach Automation is a private tool used by Novus Co. to organise business contacts, prepare Gmail drafts, send authorised emails, and record replies, delivery failures and requests not to be contacted in Novus Co. Leads.",
  "The tool connects only the owner's authorised Gmail account and the Novus Co. Leads spreadsheet. It is not open for public registration. Access is granted through Google's permission screen; Novus does not ask for a Google password.",
  "The Gmail and Sheets connection has been tested. The complete daily outreach workflow remains under development and campaign sending is currently disabled."
];

export const outreachPrivacy = [
  "Novus Co. uses a private automation tool connected by its owner to Gmail and Google Sheets. The Google permissions allow reading Gmail messages, managing drafts and sending emails, and accessing Google spreadsheets. Although Google grants spreadsheet access at account level, this automation is restricted to Novus Co. Leads.",
  "The tool uses email addresses, message content, message identifiers, sending and reply history, delivery notices, business contact records and contact preferences to prepare and manage correspondence, avoid duplicate contact, recognise replies and delivery failures, and respect requests to stop contact. A listing in our records does not by itself authorise an email to be sent.",
  "Gmail messages and drafts remain in Gmail; business records and operational history are stored in Google Sheets. Supabase provides the private automation database and execution service. Renewable Google access credentials are stored in Supabase Vault, and operational records may contain message identifiers, contact status and evidence of actions. Owner-authorised Codex tools may process relevant message and spreadsheet information while assisting with these tasks. Information is not made public by the automation.",
  "Google account data is used only for these correspondence and record-management features. Novus does not sell it, use it for advertising profiles or use it to train general-purpose AI models. Novus Outreach Automation's use and transfer of information received from Google APIs will adhere to the Google API Services User Data Policy, including its Limited Use requirements.",
  "The owner can revoke the app's Google access in Google Account settings. Revoking access stops future access but does not automatically delete existing Gmail messages, spreadsheet records or audit records. To request access, correction or deletion of information held by Novus, contact salim.novusco@gmail.com. Minimal suppression records may be retained to honour a request not to be contacted; other operational records are retained while needed for correspondence, reconciliation or applicable obligations. Deletion requests are reviewed and handled by the owner; the app does not promise automatic deletion."
];
